// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp1WUW3H4T3WqXBGeYYe9wpqldfB8VSxg',
    appId: '1:241700246642:web:fe3e7566944a70f44adeeb',
    messagingSenderId: '241700246642',
    projectId: 'capstone-c28c6',
    authDomain: 'capstone-c28c6.firebaseapp.com',
    databaseURL: 'https://capstone-c28c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstone-c28c6.appspot.com',
    measurementId: 'G-4PJ0VWPCXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYa08WarEIWb1RncltDLrdS3ogm9k4gfk',
    appId: '1:241700246642:android:472a20f89722a8cb4adeeb',
    messagingSenderId: '241700246642',
    projectId: 'capstone-c28c6',
    databaseURL: 'https://capstone-c28c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstone-c28c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi2Yn9YFr45OQv8O2ge1nLHF77uqJPmn8',
    appId: '1:241700246642:ios:aa36b780abe2265f4adeeb',
    messagingSenderId: '241700246642',
    projectId: 'capstone-c28c6',
    databaseURL: 'https://capstone-c28c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstone-c28c6.appspot.com',
    iosClientId: '241700246642-gpr0rb8ed993usffo5huh6tt82s2ie2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi2Yn9YFr45OQv8O2ge1nLHF77uqJPmn8',
    appId: '1:241700246642:ios:aa36b780abe2265f4adeeb',
    messagingSenderId: '241700246642',
    projectId: 'capstone-c28c6',
    databaseURL: 'https://capstone-c28c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstone-c28c6.appspot.com',
    iosClientId: '241700246642-gpr0rb8ed993usffo5huh6tt82s2ie2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstone',
  );
}
